server:
  port: 8080
  servlet:
    context-path:
      /backservices

spring:
  application:
    name: back-services-kotlin

  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-crimson-wave-agglnc9y-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_Jo6fK3vBEtYp}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /api-docs
